spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nowgroup_scs
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
        hbm2ddl.auto: create
